package constantes;

public abstract class Musicas {
    public static final String[] LIVING_ON_A_PRAYER =
            {"01 - Once upon a time not so long ago\n",
                    "02 - Tommy used to work on the docks, union's been on strike\n",
                    "03 - He's down on his luck, it's tough, so tough\n",
                    "04 - Gina works the diner all day working for her man\n",
                    "05 - She brings home her pay, for love, for love\n",
                    "06 - She says, we've got to hold on to what we've got\n",
                    "07 - It doesn't make a difference if we make it or not\n",
                    "08 - We've got each other and that's a lot for love\n",
                    "09 - We'll give it a shot\n",
                    "10 - Woah, we're half way there\n",
                    "11 - Woah, livin' on a prayer\n",
                    "12 - Take my hand, we'll make it I swear\n",
                    "13 - Woah, livin' on a prayer\n",
                    "14 - Tommy's got his six-string in hock\n",
                    "15 - Now he's holding in what he used to make it talk\n",
                    "16 - So tough, it's tough\n",
                    "17 - Gina dreams of running away\n",
                    "18 - When she cries in the night, Tommy whispers\n",
                    "19 - Baby, it's okay, someday\n",
                    "20 - We've got to hold on to what we've got\n",
                    "21 - It doesn't make a difference if we make it or not\n",
                    "22 - We've got each other and that's a lot for love\n",
                    "23 - We'll give it a shot\n",
                    "24 - Woah, we're half way there\n",
                    "25 - Woah, livin' on a prayer\n",
                    "26 - Take my hand, we'll make it I swear\n",
                    "27 - Woah, livin' on a prayer\n",
                    "28 - Livin' on a prayer\n",
                    "29 - Oh, we've got to hold on, ready or not\n",
                    "30 - You live for the fight when it's all that you've got\n",
                    "31 - Woah, we're half way there\n",
                    "32 - Woah, livin' on a prayer\n",
                    "33 - Take my hand, we'll make it I swear\n",
                    "34 - Woah, livin' on a prayer\n",
                    "35 - Woah, we're half way there\n",
                    "36 - Woah, livin' on a prayer\n",
                    "37 - Take my hand, we'll make it I swear\n",
                    "38 - Woah, livin' on a prayer\n",
                    "39 - Woah, we're half way there\n",
                    "40 - Woah, livin' on a prayer\n",
                    "41 - Take my hand, we'll make it I swear\n",
                    "42 - Woah, livin' on a prayer\n"};

    public static final String[] WONDERWALL =
            {"01 - Today is gonna be the day\n",
                    "02 - That they're gonna throw it back to you\n",
                    "03 - By now you should've somehow\n",
                    "04 - Realized what you gotta do\n",
                    "05 - I don't believe that anybody\n",
                    "06 - Feels the way I do, about you now\n",
                    "07 - Backbeat, the word was on the street\n",
                    "08 - That the fire in your heart is out\n",
                    "09 - I'm sure you've heard it all before\n",
                    "10 - But you never really had a doubt\n",
                    "11 - I don't believe that anybody\n",
                    "12 - Feels the way I do about you now\n",
                    "13 - And all the roads we have to walk are winding\n",
                    "14 - And all the lights that lead us there are blinding\n",
                    "15 - There are many things that I\n",
                    "16 - Would like to say to you but I don't know how\n",
                    "17 - Because maybe, you're gonna be the one that saves me\n",
                    "18 - And after all, you're my wonderwall\n",
                    "19 - Today was gonna be the day\n",
                    "20 - But they'll never throw it back to you\n",
                    "21 - By now you should've somehow\n",
                    "22 - Realized what you're not to do\n",
                    "23 - I don't believe that anybody\n",
                    "24 - Feels the way I do, about you now\n",
                    "25 - And all the roads that lead you there are winding\n",
                    "26 - And all the lights that light the way are blinding\n",
                    "27 - There are many things that I\n",
                    "28 - Would like to say to you but I don't know how\n",
                    "29 - I said maybe, you're gonna be the one that saves me\n",
                    "30 - And after all, you're my wonderwall\n",
                    "31 - I said maybe, you're gonna be the one that saves me\n",
                    "32 - And after all, you're my wonderwall\n",
                    "33 - I said maybe, you're gonna be the one that saves me\n",
                    "34 - you're gonna be the one that saves me\n",
                    "35 - you're gonna be the one that saves me\n"};
}
